globals:
  seed: 1213
  device: cuda
  num_epochs: 2000
  output_dir: output/gravity

data:
  train:
    size: 1000
    type: GravitySimulation
    savedir: data/train
    params:
      n_objects: 6
      timestep: 0.001
      n_steps: 1000
      orbital:
        - True
        - False
  valid3:
    size: 66
    type: GravitySimulation
    savedir: data/val3
    params:
      n_objects: 3
      timestep: 0.001
      n_steps: 1000
      orbital:
        - True
        - False
  valid6:
    size: 67
    type: GravitySimulation
    savedir: data/val6
    params:
      n_objects: 6
      timestep: 0.001
      n_steps: 1000
      orbital:
        - True
        - False
  valid12:
    size: 66
    type: GravitySimulation
    savedir: data/val12
    params:
      n_objects: 12
      timestep: 0.001
      n_steps: 1000
      orbital:
        - True
        - False
  test3:
    size: 66
    type: GravitySimulation
    savedir: data/test3
    params:
      n_objects: 3
      timestep: 0.001
      n_steps: 1000
      orbital:
        - True
        - False
  test6:
    size: 67
    type: GravitySimulation
    savedir: data/test6
    params:
      n_objects: 6
      timestep: 0.001
      n_steps: 1000
      orbital:
        - True
        - False
  test12:
    size: 66
    type: GravitySimulation
    savedir: data/test12
    params:
      n_objects: 12
      timestep: 0.001
      n_steps: 1000
      orbital:
        - True
        - False

model:
  name: IN
  params:
    relation:
      shapes:
        - 11
        - 150
        - 150
        - 150
        - 100
    object:
      shapes:
        - 105
        - 100
        - 2

loss:
  name: MSELoss

optimizer:
  name: Adam
  params:
    lr: 0.001

scheduler:
  name: ReduceLROnPlateau
  params:
    patience: 40
    verbose: True
    factor: 0.8

loader:
  train:
    batch_size: 100
    shuffle: True
    num_workers: 8
  valid3:
    batch_size: 100
    shuffle: False
    num_workers: 8
  valid6:
    batch_size: 100
    shuffle: False
    num_workers: 8
  valid12:
    batch_size: 100
    shuffle: False
    num_workers: 8
  test:
    batch_size: 100
    shuffle: False
    num_workers: 8
